Add basic UI
codecaiine/oop-school-library pull request #4
Opened 2021-11-18 15:35 UTC by codecaiine

- Created a main.rb file that serves as console app entry-point.
- Created menu list in main.rb

2021-11-18 16:01 UTC, od-c0d3r requested changes
# Status: Changes Required ♻️

Asslam Alikom @codecaiine  👋😄,
I'm Omar and I will be your reviewer for this project 😊

Good job so far!👌😃, There are some issues 🐞 that you still need to work on to go to the next project but you are almost there! 🏁🏁🏁

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-18 16:01 UTC, o-rashad commented on main.rb
> +    student = Student.new(age, @class, name, parent_permission)
Well done creating all these interacting methods :100: ,
Unfortunately i ran into this error when i try to create a `student` instance :disappointed:  
> ![FireShot Capture 004 - main rb - oop-school-library - Gitpod Code_ - copper-sparrow-66g6q7js ws-eu18 gitpod io](https://user-images.githubusercontent.com/24830039/142450771-9dc88de1-ba6c-4c79-a00e-c64747c40ea7.png)

- - [x] Investigate the error and solve the issue. :+1:

2021-11-18 21:41 UTC, codecaiine commented on main.rb
> +    student = Student.new(age, @class, name, parent_permission)
Alaikum salam @od-c0d3r
Nice to meet you Omar and thank you for reviewing my code and for your comments. I was able to implement all required changes as you can see below:
![teseeeet](https://user-images.githubusercontent.com/6615394/142501228-6e1179b5-7a07-4d50-9f81-b9e17af55403.PNG)
![T2](https://user-images.githubusercontent.com/6615394/142501242-152802db-e6c1-4c47-8de9-67a790cc4e3a.PNG)
![T1](https://user-images.githubusercontent.com/6615394/142501260-70cb319b-2f68-4e81-9ca8-b838a49f0588.PNG)
![TESSSSS](https://user-images.githubusercontent.com/6615394/142501273-f4ff49b5-d5ce-46d5-b3ae-e1e4e66d72f6.PNG)

2021-11-18 22:10 UTC, mke2111 approved these changes
### Hi @codecaiine, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-18 22:21 UTC, codecaiine commented
Hi @mke2111 ,

Thank you for reviewing my work and approving it.

Cheers!

2021-11-18 22:21 UTC, merged

2021-11-19 05:10 UTC, od-c0d3r commented on main.rb
> +    student = Student.new(age, @class, name, parent_permission)
Thanks @codecaiine :wave: for your feedback.
Sorry for the inconvenience.

- [ ] Now I need to investigate my error and solve it :sweat_smile:

2021-11-19 05:34 UTC, od-c0d3r commented on main.rb
> +    student = Student.new(age, @class, name, parent_permission)
@codecaiine Keep it up :100: :chart:

2021-11-19 07:06 UTC, codecaiine commented on main.rb
> +    student = Student.new(age, @class, name, parent_permission)
Thanks Omar :)